FROM python:3
ENV PYTHONUNBUFFERED 1
ENV WORKDIR /code/

RUN pip install --upgrade pip
RUN pip install pipenv==2018.11.26
RUN mkdir ${WORKDIR}
WORKDIR ${WORKDIR}
# COPY requirements.txt /code/
COPY Pipfile Pipfile.lock ${WORKDIR}
# RUN pip install -r requirements.txt
RUN pipenv install --deploy --system
COPY . ${WORKDIR}